version: '3.3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123

  web:
          #    build: ./Dockerfile
          #    command: python manage.py runserver 0.0.0.0:8000
    image: task_manager:v2
    #    volumes:
    #      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
